FROM python:3.10

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

WORKDIR /rest_api

RUN pip install --upgrade pip && pip install poetry

COPY ../../pyproject.toml /rest_api/
COPY ../../pyproject.toml /rest_api/

RUN poetry config virtualenvs.create true  \
    && poetry config virtualenvs.in-project true  \
    && poetry install --no-interaction --no-ansi --no-root

COPY ../../ .

